// <auto-generated />
using System;
using Daqifi.Desktop.Logger;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Daqifi.Desktop.Migrations;

[DbContext(typeof(LoggingContext))]
[Migration("20260714120000_DropChannelTable")]
partial class DropChannelTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

        modelBuilder.Entity("Daqifi.Desktop.Channel.DataSample", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ChannelName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Color")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceSerialNo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("LoggingSessionID")
                    .HasColumnType("INTEGER");

                b.Property<long>("TimestampTicks")
                    .HasColumnType("INTEGER");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.Property<double>("Value")
                    .HasColumnType("REAL");

                b.HasKey("ID");

                b.HasIndex("LoggingSessionID", "TimestampTicks")
                    .HasDatabaseName("IX_Samples_SessionTime");

                b.ToTable("Samples", (string)null);
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.LoggingSession", b =>
            {
                b.Property<int>("ID")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long?>("SampleCount")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("SessionStart")
                    .HasColumnType("TEXT");

                b.HasKey("ID");

                b.ToTable("Sessions", (string)null);
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.SessionDeviceMetadata", b =>
            {
                b.Property<int>("LoggingSessionID")
                    .HasColumnType("INTEGER");

                b.Property<string>("DeviceSerialNo")
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("SamplingFrequencyHz")
                    .HasColumnType("INTEGER");

                b.HasKey("LoggingSessionID", "DeviceSerialNo");

                b.ToTable("SessionDeviceMetadata", (string)null);
            });

        modelBuilder.Entity("Daqifi.Desktop.Channel.DataSample", b =>
            {
                b.HasOne("Daqifi.Desktop.Logger.LoggingSession", "LoggingSession")
                    .WithMany("DataSamples")
                    .HasForeignKey("LoggingSessionID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LoggingSession");
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.SessionDeviceMetadata", b =>
            {
                b.HasOne("Daqifi.Desktop.Logger.LoggingSession", "LoggingSession")
                    .WithMany("DeviceMetadata")
                    .HasForeignKey("LoggingSessionID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LoggingSession");
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.LoggingSession", b =>
            {
                b.Navigation("DataSamples");

                b.Navigation("DeviceMetadata");
            });
#pragma warning restore 612, 618
    }
}
