// <auto-generated />
using System;
using Daqifi.Desktop.Logger;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Daqifi.Desktop.Migrations;

[DbContext(typeof(LoggingContext))]
[Migration("20260414120000_AddSessionDeviceMetadata")]
partial class AddSessionDeviceMetadata
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

        modelBuilder.Entity("Daqifi.Desktop.Channel.Channel", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActiveSampleID")
                    .HasColumnType("INTEGER");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceSerialNo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Direction")
                    .HasColumnType("INTEGER");

                b.Property<bool>("HasAdc")
                    .HasColumnType("INTEGER");

                b.Property<bool>("HasValidExpression")
                    .HasColumnType("INTEGER");

                b.Property<int>("Index")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsAnalog")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsBidirectional")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDigital")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDigitalOn")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsOutput")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsScalingActive")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsVisible")
                    .HasColumnType("INTEGER");

                b.Property<int?>("LoggingSessionID")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<double>("OutputValue")
                    .HasColumnType("REAL");

                b.Property<string>("ScaleExpression")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.Property<string>("TypeString")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("ID");

                b.HasIndex("ActiveSampleID");

                b.HasIndex("LoggingSessionID");

                b.ToTable("Channel");
            });

        modelBuilder.Entity("Daqifi.Desktop.Channel.DataSample", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ChannelName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Color")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceSerialNo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("LoggingSessionID")
                    .HasColumnType("INTEGER");

                b.Property<long>("TimestampTicks")
                    .HasColumnType("INTEGER");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.Property<double>("Value")
                    .HasColumnType("REAL");

                b.HasKey("ID");

                b.HasIndex("LoggingSessionID");

                b.HasIndex("LoggingSessionID", "TimestampTicks")
                    .HasDatabaseName("IX_Samples_LoggingSessionID_TimestampTicks");

                b.ToTable("Samples");
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.LoggingSession", b =>
            {
                b.Property<int>("ID")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("SessionStart")
                    .HasColumnType("TEXT");

                b.HasKey("ID");

                b.ToTable("Sessions");
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.SessionDeviceMetadata", b =>
            {
                b.Property<int>("LoggingSessionID")
                    .HasColumnType("INTEGER");

                b.Property<string>("DeviceSerialNo")
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("SamplingFrequencyHz")
                    .HasColumnType("INTEGER");

                b.HasKey("LoggingSessionID", "DeviceSerialNo");

                b.ToTable("SessionDeviceMetadata");
            });

        modelBuilder.Entity("Daqifi.Desktop.Channel.Channel", b =>
            {
                b.HasOne("Daqifi.Desktop.Channel.DataSample", "ActiveSample")
                    .WithMany()
                    .HasForeignKey("ActiveSampleID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Daqifi.Desktop.Logger.LoggingSession", null)
                    .WithMany("Channels")
                    .HasForeignKey("LoggingSessionID");

                b.Navigation("ActiveSample");
            });

        modelBuilder.Entity("Daqifi.Desktop.Channel.DataSample", b =>
            {
                b.HasOne("Daqifi.Desktop.Logger.LoggingSession", "LoggingSession")
                    .WithMany("DataSamples")
                    .HasForeignKey("LoggingSessionID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LoggingSession");
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.SessionDeviceMetadata", b =>
            {
                b.HasOne("Daqifi.Desktop.Logger.LoggingSession", "LoggingSession")
                    .WithMany("DeviceMetadata")
                    .HasForeignKey("LoggingSessionID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LoggingSession");
            });

        modelBuilder.Entity("Daqifi.Desktop.Logger.LoggingSession", b =>
            {
                b.Navigation("Channels");

                b.Navigation("DataSamples");

                b.Navigation("DeviceMetadata");
            });
#pragma warning restore 612, 618
    }
}
